### ISSUE TITLE
Entry Page

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#1]
## Value proposition

As an User
I want to see the content of an entry
So that I can read and edit the content

## Description

![Image](https://github.com/vaupunkt/cbaspCompanion/assets/119793693/42aed6d4-773c-4a35-a895-bb8dbd517c5e)

## Acceptance criteria

- [x] Have a `title` at the top
- [x] have the `title` fixed to stay at top
- [x] have the date of the `entry` displayed
- [x] Have the content of the `entry` displayed
- [x] have smaller headlines for each category

## Tasks

- [x] create a `title`
- [x] make it `fixed` on top of the screen
- [x] display the content of the entry with `labels`
- [x] display the date of the entry beneath the header

**Comment by AliaksandraNovikava** [comment]
LGTM 👍
One small thing: maybe you could remove the edit icon from your wireframe if you don't have it in your acceptance criteria.

**Comment by vaupunkt** [comment]
yes - i will update it :)
