### ISSUE TITLE
Delete Button on Entry Page

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#10]
## Value proposition

As an User
I want a Delete Button on the Entry-Page
So that I can delete the opened entry

## Description

![Image](https://user-images.githubusercontent.com/119793693/251695511-ac3b1654-133c-4cfb-9c26-d83b08934f3d.png)

![Image](https://user-images.githubusercontent.com/119793693/251696035-f6fe14d4-4ae4-4d06-b656-a65873b58278.png)

![Image](https://user-images.githubusercontent.com/119793693/251695792-80c257c5-bead-4712-8672-c8cd3220dbd4.png)

## Acceptance criteria

- [x] I want a `button` to delete the whole `entry`
- [x] the `button` is at the top of the entry under the `header`
- [x] the `button` opens a window, where i get asked if i am sure to delete this entry
- [x] if i click yes, the entry gets deleted from the data array and i will be automatically redirected to my overview of entries

## Tasks

- [x] Create a button to delete an entry.
- [x] Place the button at the top of the entry under the header.
- [x] Make sure that when clicked, a window pops up asking if you are sure you want to delete this entry.
- [x] If yes is clicked, delete the entry from the data array.
- [x] Automatically redirect to overview of entries after deletion.

**Comment by CorneliusMoe** [comment]
Looks very good. I really like your App so far😁
