### ISSUE TITLE
Edit Entry

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#11]
## Value proposition

As an User
I want a Edit-Button
So that I can edit entries if I made mistake or want to change something

## Description

![Image](https://github.com/vaupunkt/cbaspCompanion/assets/119793693/14a26ff8-ca42-4314-82fa-f018c4342d48)

![Image](https://user-images.githubusercontent.com/119793693/251704589-4b97c16d-1c8e-4167-b159-fc98049f60c4.png)

![Image](https://user-images.githubusercontent.com/119793693/251704765-bbf33748-144b-4c9d-9781-29e7dc859fcd.png)

## Acceptance criteria

- [x] The `edit button` should be visible on the `Entry-Page`.
- [x] The `edit button` should be clickable.
- [x] When the `edit button` is clicked, the user should be able to `edit` the entries.
- [x] The user should be able to `save` the changes made.

## Tasks

- [x] Create a new `component` for the `Edit button`.
- [x] Add the `Edit button` component to the page.
- [x] Implement the functionality for the `Edit button`.
- [x] Implement the change of the Edit-Button to a Save-Butten
- [x] Implement the functionality for editing entries.
- [x] Implement the functionality for saving changes made to the `data array`.
