### ISSUE TITLE
New VergangenheitsAnalyse-Form

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#16]
# New VergangenheitsAnalyse-Form

## Value proposition

As an User
I want to click on "Vergangenheitsanalyse"
So that I can start filling out everything for a new Vergangenheitsanalyse/Past-Analysis

## Description

![Image](https://github.com/vaupunkt/cbaspCompanion/assets/119793693/7a3bdb05-7616-4ed1-a5d5-d201d5e0fca1)

## Acceptance criteria

- [x] have the `fields` to be required so i can not `submit` an empty `form`
- [x] take at least 1 interpretation
- [x] have a max. amount of symbols on the `input fields`
- [x] have the max. amount set to 500 for tall fields and to 200 for shorter inputs
- [x] in the revision part have fields with the interpretations as values and the possibility for me to revise these interpretations and change them
- [x] on `submit` save the files to an array "entries" with an unique `id` and `type: "PastAnalysis",`
- [x] use the `entry-component` to display the submitted data under the form

## Tasks
- [x] Create a new form called “PastAnalysisForm”.
- [x] Add fields to the form and make them required so that the user cannot submit an empty form.
- [x] Have at least one interpretation field as required.
- [x] Set the maximum amount of symbols to 500 for tall fields and 200 for shorter inputs.
- [x] Add fields revision with the interpretations as values and the possibility for the user to revise these interpretations
- [x] Save the files to an array “entries” with a unique id and type: “PastAnalysis” on submit.
- [x] Use the entry-component to display the submitted data under the form.

**Comment by julialoeschel** [comment]
Hey there! 

I think this is a userstorry that should be at least three stories :) 
plus the submit does not lead to the display of the data anywhere. The user basically sends all the information nowhere. 

what I suggest is: 
- 1 US is the form (no "add more"-functionality, no "why not"-modal) 
        - the data shall be displayed somewhere. The easiest way is to display the data underneath the form in the same page. 
- 1 US for adding a new input field when the button is clicked
- 1 US for the modal

Also the heading Tasks is missing with all its information.

**Comment by vaupunkt** [comment]
@julialoeschel thank you for the review! I trimmed down the UserStory and will split it into three parts. The top/heading was part of another user story :)

**Comment by julialoeschel** [comment]
great :) 
without viewing the content in Detail - I see that still TASKS are missing. 
try to check out other peoples USs to see what I mean. 
🚀

**Comment by dimitriosxmi** [comment]
Tasks are still missing

**Comment by CarstenJahnke** [comment]
Wow, what a huge page, maybe you could move the from elements to individual pages so it doesn't seem too huge to the user? Otherwise very extensive your page 🙏🏻

**Comment by vaupunkt** [comment]
@CarstenJahnke hey :) in a future UserStory I am going to convert that huge form into a conversational form, like a chatbot with several steps. right now i just want to implement the pure functionality of the form  👨🏼‍💻
