### ISSUE TITLE
New InnereSituationsanalyse-Form

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#17]
## Value proposition

As an User
I want to click on "Innere Situationsanalyse"
So that I can start filling out everything for a new Innere Situationsanalyse/InnerSituationAnalysis

## Description

![Image](https://github.com/vaupunkt/cbaspCompanion/assets/119793693/becbe717-f9eb-4a48-a14c-180ddbf0c344)

## Acceptance criteria

- [x] have the `fields` to be required so i can not `submit` an empty `form`
- [x] take at least 1 interpretation
- [x] have a max. amount of symbols on the `input fields`
- [x] have the max. amount set to 500 for tall fields and to 200 for shorter inputs
- [x] in the revision part have fields with the interpretations as values and the posibility for me to revise these interpretations and change them
- [x] on `submit` save the files to an array "entries" with an unique `id` and `type: "InnerSituationAnalysis"`
- [x] use the `entry-component` to display the submitted data under the form

## Tasks

- [x] create the if-case to render the form by click on the `radio`-button "Innere Situationsanalyse"
- [x] render the `form` for the Innere Situationsanalyse by using `descriptions` and `headlines` according to the analysis-`type`
- [x] create `input`-fields and give them the prop `long` or `short`
- [x] give the `long-input-fields` the `maxlength` 500
- [x] give the `short-input-fields` the `maxlength` 200
- [x] create a `submit`-function
- [x] add the data to` allEntries` with `destructuring` and `setAllEntries`
- [x] redirect in the `submit`-function to the `entry-page` by using the` [id].js-dynamic-route`

**Comment by Dariastep** [comment]
Very good and detailed US. Nice! ✨
