### ISSUE TITLE
new Zukunftsanalyse-Form

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#18]
## Value proposition

As an User
I want to click on "Zukunftsanalyse"
So that I can start filling out everything for a new  Zukunftsanalyse/FutureAnalysis

## Description

![Image](https://user-images.githubusercontent.com/119793693/252312461-de68523a-3f26-4d2b-8b35-a5a18259179b.png)

## Acceptance criteria

- [x] have the `fields` to be required so i can not `submit` an empty `form`
- [x] take at least 1 interpretation
- [x] have a max. amount of symbols on the `input fields`
- [x] have the max. amount set to 500 for tall fields and to 200 for shorter inputs
- [x] on `submit` save the files to an array "entries" with an unique `id` and the `type="FutureAnalysis"`
- [x] redirect the user after the click to the page with the entry

## Tasks

- [x] create the if-case to render the form by click on the radio-button "zukunftsanalyse"
- [x] render the `form` for the zukunftsanalyse by using `descriptions` and `headlines` according to the analysis-`type`
- [x] create `input`-fields and give them the prop `long` or `short`
- [x] give the `long-input-fields` the `maxlength` 500
- [x] give the `short-input-fields` the `maxlength` 200
- [x] create a `submit`-function
- [x] add the data to` allEntries` with `destructuring` and `setAllEntries`
- [x] redirect in the `submit`-function to the `entry-page` by using the` [id].js-dynamic-route`

**Comment by Dariastep** [comment]
SAme here, very detailed and good US!😀
