### ISSUE TITLE
All Entries Page

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#2]
## Value proposition

**As an** user
**I want** to see all my entries that i made
**So that** I can view them

## Description

![Image](https://github.com/vaupunkt/cbaspCompanion/assets/119793693/a883b532-df66-4df4-a425-bf0924ca8dac)

## Acceptance criteria

- [x] without entries show a placeholder "no entries yet"
- [x] I want to see a `list` of my entries, if there are any
- [x] I want to be able to `click` on the entry to show its content on the entry-page
- [x] I want to see a `back button` on the entry-page, that takes me back to all entries

## Tasks

- [x] Add a `heading`
- [x] Add a `list` with entries
- [x] `if` the list is empty, show a placeholder
- [x] have the list item to show its name and date of the entry

**Comment by JessicaLoers** [comment]
Hi @vaupunkt ✌️

In my opinion this user story can/should be divided into two smaller ones. 
The word "and" (third line of your Value Proposition) is often an indicator that a user story wants to cover two features at once.

I recommend you to implement the delete functionality in a separate User Story.
