### ISSUE TITLE
add more Interpretations

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#29]
## Value proposition

As an User
I want a button
So that I can add more Interpretations in the forms where I add new analyses

## Description

![Image](https://user-images.githubusercontent.com/119793693/253880206-cbdc2a40-8d12-4c1f-9f3d-1f3bdfc61069.png)

![Image](https://user-images.githubusercontent.com/119793693/253880733-d6085b20-0bd1-4632-a2f2-167a8fb5cf75.png)

## Acceptance criteria

- [x] in the form at the interpretations-point give the user a button
- [x] have three interpretations as standard
- [x] let the user `add more` than standard three interpretations
- [x] after a click more input fields appear

## Tasks
- [x] add a `button` in the `interpretations-section`
- [x] give it a text "mehr Interpretationen hinzufügen"
- [x] write a `function` that adds a input field above the button
- [x] the input field should be inside the `<ol>`of the interpretations-section

**Comment by itsandeepsingh** [comment]
lgtm :)
