### ISSUE TITLE
Zukunftsanalysen-Page

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#3]
## Value proposition

As an user
I want a see a list with the "Zukunftsanalysen"
So that concentrate on reading only them

## Description

![Image](https://user-images.githubusercontent.com/119793693/251420686-51600f48-fc70-481d-bf43-7da0bc63d163.png)

## Acceptance criteria

- [ ] I want to have `delete button/option` (will be an own US)
- [x] I want to be able to `click` on the `entry` to show its content on the entry-page
- [x] I want to see a `back button` on the entry-page, that takes me back to all "Zukunftsanalysen"

## Tasks

- [x] Add a `heading`
- [x] Add a list with entries that have the `type: "FutureAnalysis"`
- [ ] have the option to `delete` a `entry` (will be an own US)
- [x] have the `list item` to show its `name` and `date` of the `entry`
- [x] have the entry in the list `clickable` so i reach the single entry page
- [x] have a `back button `on the `entry page`, that takes me back to the overview

**Comment by DErdmann1** [comment]
Love your Project! Your US looks great :)
