### ISSUE TITLE
remove more interpretations

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#30]
## Value proposition

As an user
I want a button
So that i can delete unused interpretations if I added to many

## Description

![Image](https://user-images.githubusercontent.com/119793693/253880927-9eb9dfc1-e444-4c19-a790-0165cd6fbf9f.png)

![Image](https://github.com/vaupunkt/cbaspCompanion/assets/119793693/75a1ac11-a611-4ccb-9a33-3e3b579152eb)

## Acceptance criteria

- [x] with a click on the x-button delete the added interpretations
- [x] always have at least 3 interpretation-fields, only be able to delete the "extra"/added ones
- [x] get asked if the user is sure to delete

## Tasks

- [x] have a `delete-button` next to the added input-field to remove the added field
- [x] have a pop up appear 
- [x] have the user asked if he is sure to delete
- [x] make the input field disappear after a click on delete

**Comment by itsandeepsingh** [comment]
The delete button should also be shown if there is something in the "Input Field"? Is there a Pop-Up warning if you want to delete an "input field" that contains something? Something like, "Are you sure you want to delete it"?
May be define the acceptance criteria more precisely :)

**Comment by matschi3** [comment]
looks good 🚀
