### ISSUE TITLE
wanted outcome - extra field

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#31]
## Value proposition

As an User
I want a extra-input
So that I can write why I didn't reach my wanted outcome in an situation

## Description

![Image](https://user-images.githubusercontent.com/119793693/253881891-066cd173-a049-4ac9-b055-74566433e57e.png)

## Acceptance criteria

- [x] add the radio buttons and the functionality to the input forms "Vergangenheitsanalyse", Zukunftsanalyse" "Innere Situationsanalyse"
- [x] I want a Yes and No button/radio-Input on the question "Did I reach my wanted outcome?"
- [x] with a click on no i want a input-field where I can write the reason why the wanted outcome was not reached

## Tasks

- [x] have two `radio buttons`
- [x] let them say `"Ja"` and `"Nein"`
- [x] with a click on "Nein" an Input appears
- [x] make it `long` and `required`
- [x] `maxLength = 500`

**Comment by matschi3** [comment]
when taking a look at your app i assume this is part of a `Form` so it don't need any submit for itself.
Maybe add to your Acceptance Criteria where this new things will be ✌🏼
Otherwise clean and easy US ✓
