### ISSUE TITLE
add more actionInterpretations

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#32]
## Value proposition

As an User
I want to get "Action Interpretations" from older analyses as I type
So that I can see and choose previous Action Interpretations if one fits for this analysis again

## Description

![Image](https://user-images.githubusercontent.com/119793693/253884398-d47df18d-4090-4363-a686-05d5bacce7da.png)

## Acceptance criteria

- [x] add the input & functionality to the input forms "Vergangenheitsanalyse", Zukunftsanalyse" "Innere Situationsanalyse"
- [x] let the user type into the input field
- [x] As the user types have a dropdown appear where he can choose fitting interpretations

## Tasks

- [x] create a array with all older actionInterpretations
- [x] with onChange or onInput create a function that searches the array for the string the user inputs

**Comment by matschi3** [comment]
nice small US ✓ although i think you will have enough to code with this :)

Also here for Acceptance Criteria: just tell where/on which side this all will happen and you're good to go
🚀
(you can message me when added, so i can give you the ✅)
