### ISSUE TITLE
Vergangenheitsanalysen-Page

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#4]
## Value proposition

As an user
I want to see a list with the "Vergangenheitsanalysen"
So that I can concentrate on reading only them

## Description

![Image](https://user-images.githubusercontent.com/119793693/251422077-8ae56edf-6506-4b88-a7f2-bb57c32be9bc.png)

## Acceptance criteria

- [x] I want to have `delete button/option`
- [x] I want to be able to `click` on the `entry` to show its content on the entry-page
- [x] I want to see a `back button` on the entry-page, that takes me back to all "Vergangenheitsanalysen"

## Tasks

- [x] Add a `heading`
- [x] Add a list with entries that have the `type: "PastAnalysis"`
- [x] have the option to `delete` a `entry`
- [x] have the `list item` to show its `name` and `date` of the `entry`
- [x] have the entry in the list `clickable` so i reach the single entry page
- [x] have a `back button `on the `entry page`, that takes me back to the overview

**Comment by MonaHer** [comment]
I'm so curious about your app - sounds like Freud would code it :)

I guess there are two little typos in the value proposition: 

As an user
I want **to** see a list with the "Vergangenheitsanalysen"
So that **I can** concentrate on reading only them

**Comment by vaupunkt** [comment]
yes you are right! i will edit it 👍
