### ISSUE TITLE
Innere-Analysen-Page

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#5]
## Value proposition

As an user
I want a see a list with the "Innere-Analysen"
So that I can see all "Innere Analysen"

## Description

![Image](https://user-images.githubusercontent.com/119793693/251422619-b49f2853-ac66-46e9-a595-8bc9edf1317b.png)

## Acceptance criteria

- [x]  I want to see a list with all entries with the `type: "InnerSituationAnalysis"`
- [x] I want to see a heading with "Innere Analysen"
- [x] I want to be able to `click` on the `entry` to show its content on the` entry-page` from [US1](https://github.com/users/vaupunkt/projects/2/views/1?pane=issue&itemId=32508091)
- [x] I want to see a `back button` on the entry-page, that takes me back to all "Innere-Analysen"

## Tasks

- [x] Add a `heading`
- [x] Add a list with entries that have the `type: "InnerSituationAnalysis"`
- [x] have the `list item` to show its `name` and `date` of the `entry`
- [x] have the entry in the list `clickable` so i reach the single entry page
- [x] have a `back button `on the `entry page`, that takes me back to the overview

**Comment by josch87** [comment]
The acceptance criteria are not complete. Do the developers need to code a list or is the list already created in a former user story? Do they need to add a heading for the list-page? etc.

**Comment by vaupunkt** [comment]
i updated the acceptance criteria :)

**Comment by JessicaLoers** [comment]
Hi @vaupunkt ✌️

As I mentioned in the comment of US 2, in my opinion this user story can/should be divided into two smaller ones. (List of "Innere-Analyse" and delete functionality of each list item). 

Since you have now reached your fourth list page (All Entries Page, Zukunftsanalyse Page, Vergangenheitsanalysen Page, Innere Analysen Page) I would strongly recommend that you at least include the delete function in the value proposition for this user story, as it is completely missing.

**Comment by vaupunkt** [comment]
@JessicaLoers I am going to create a user story for the deletebutton :)

**Comment by djfarly** [comment]
I think you're good now :)
