### ISSUE TITLE
My Analyses Page

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#6]
## Value proposition

As an User
I want a Page for my different types of analyses
So that I can filter for the different analyses and to find all

## Description

![Image](https://user-images.githubusercontent.com/119793693/251430172-c2ad8f79-3ef4-4fc2-8a1e-09c29143310c.png)

## Acceptance criteria

- [x] Have a `heading`
- [x] have three `buttons` for "Zukunftsanalysen", "Vergangenheitsanalysen", "Innere Situationen"
- [x] have the buttons lead to the different `list-pages`
- [x] have a `button` to see all analyses

## Tasks

- [x] add `heading`
- [x] add `"Zukunftsanalysen"-Button`
- [x] add `"Vergangenheitsanalysen"-Button`
- [x] add `"Innere Situationen"-Button`
- [x] add` "alle" Button`
- [x] add a link to each `button` for the different `list pages`:
> 1. [ ] pages/futureanalyses
> 2. [ ] pages/pastanalyses
> 3. [ ] pages/inneranalyses

**Comment by ghost** [comment]
hello, afaik there should only be buttons with a function. Are there already Analyses to see? What will happen, if the user presses the button? Maybe it would be great to create a component "Zukunftsanalysen" and then the button to open this.
Cheers, Jonas

**Comment by vaupunkt** [comment]
hey @JonasDaJones, I added the aspect, that these buttons link to the different pages where the list of the specific analysis is displayed :)
Thank you!

**Comment by djfarly** [comment]
Please note that even if you call it buttons here, they technically should probably be links if they link to a different page. 📄
