### ISSUE TITLE
Delete Button on List-Page

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#7]
## Value proposition

As an user
I want a `delete-button`
So that I can delete unwanted `entries` on the `list-pages`

## Description

![Image](https://github.com/vaupunkt/cbaspCompanion/assets/119793693/c59756fb-01c1-46a1-afe7-6354a0e25bec)

![Image](https://user-images.githubusercontent.com/119793693/251459069-5774511a-e666-4587-8a4a-85769d91d8ed.png)
Delete Button

![Image](https://user-images.githubusercontent.com/119793693/251459330-db099f77-8225-4802-8b9b-18b3b6e439b6.png)

![Image](https://github.com/vaupunkt/cbaspCompanion/assets/119793693/b4d88a58-e2fd-4f5e-96d1-be69266e2d03)

## Acceptance criteria

- [x] i want an edit button to toggle the delete function
- [x] when toggled, I want a `button` on top of the specific `entries`
- [x] I want to `click` it
- [x] I want a popup to appear that asks me if i am sure to delete this entry
- [x] When the `"Löschen"-Button` is pressed, the entry gets deleted from the data-array
- [x] the `"Löschen"-Button` should be red
- [x] have a `"Abbrechen" Button` to cancel 

## Tasks

- [x] create the edit button
- [x] give every entry a `delete-button-component`
- [x] create a popup, that asks the User if he is sure to `delete` the entry
- [x] if `Löschen` is pressed delete the entry from the data-array
- [x] if `Abbrechen` is pressed return to the list
- [x] use destructuring to delete the selected entry from the data array

**Comment by josch87** [comment]
For the value proposition can you think of a more domain driven reason why you want to delete an entry? The professional reason (der fachliche Grund) should be recognizable to the developers. For example: in order to get rid of entries that I do not need anymore (or to get rid of accidentally created duplicate entries...). 

In terms of UI/UX it could be better for the "Ja" button to display "Delete" instead and to be red for example (at least not green). And it could also have a trash icon that supports its functionality. 

I would add to the AC what happens when you click "Ja" and "Nein" in the modal. For example:

- The delete-modal is displaying a button that says "Löschen" in a danger color
- Clicking on the "Delete" button deletes the related entry (or sets a delete flag if you just want to hide it from the user - tell the developer what the behaviour should be in the system/backend, not just what the user thinks that is going to happen or is happening on the frontend only)
- The delete-modal is displaying a button that says "Nein"
- Clicking on the "Nein" button closes the modal without any changes to the data

Again: Most of the tasks you currently are listing should be acceptance criteria as the developers write their tasks based on the acceptance criteria they get from the PO.

**Comment by vaupunkt** [comment]
Thank you for the input! :) 
I tried to make it more clear with the button component and the popup window
