### ISSUE TITLE
Startpage/Homepage

### ISSUE THREAD

**Issue by vaupunkt** [vaupunkt/cbaspCompanion#8]
## Value proposition

As an User
I want to see a start-screen
So that I can go to "My Analyses" and choose there between my different analyses (right now from the data-array)

## Description

![Image](https://user-images.githubusercontent.com/119793693/251487717-8d2b0f07-a442-454b-9855-91cc7700c394.png)

## Acceptance criteria

- [x] I want to a `button` on the page that redirects me to my analyses overview
- [x] I want to be able to click on it

## Tasks

- [x] Create the home-page at ` pages/index.js`
- [x] create a `button` "Meine Analysen"
- [x] redirect me to the page "Meine Analysen" from [US6 ](https://github.com/users/vaupunkt/projects/2/views/1?pane=issue&itemId=32498965)- `pages/myanalyses`

**Comment by DErdmann1** [comment]
lgtm :)
